### ISSUE TITLE
Errors in `app.styles.scss` make whole CSS bundling fail silently

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [rothsandro/eleventy-notes#75]
# Initial message <sub>(still important)</sub>

Genuinely don't know what's happening. When I add
```scss
@font-face {
    font-family: 'Shantell Sans';
    font-display: swap;
    font-weight: 400;
    src: url('/fonts/ShantellSans-Regular.woff2') format('woff2'), local('ShantellSans');
}
```
11ty silently stops writing CSS files `app.${color}.css`. Rebuilding results into a dist folder without any CSS. Logs are silent. But once I remove the `@font-face`, it works fine.

# Solution to my problem

Looking at `bundle-css.js` I understood that you need to add `./../../` to the beginning of each URL so it finds the font file. You also don't need to passthrough-copy it; Sass (or something else internal) will bundle it. How nice is that.

# Still an issue
If anything happens with scss, you're left with no CSS at all, and with no logs.
